/**
 * Kiler API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdminServiceAdminNeighborResponse } from './admin-service-admin-neighbor-response';


export interface AdminServiceRegionResponse { 
    id?: number;
    name?: string | null;
    code?: string | null;
    freeDelivery?: boolean;
    freeDeliveryAmount?: number;
    timeSlotGenerationWindow?: number;
    lastTimeSlotGeneratedDate?: string;
    minimunCartAmount?: number;
    regionMail?: string | null;
    active?: boolean;
    neighborhoods?: Array<AdminServiceAdminNeighborResponse> | null;
}

