/**
 * Kiler API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CustomerServiceRAddress } from './customerServiceRAddress';


export interface CustomerServiceRCustomer { 
    id?: number;
    customerName?: string | null;
    customerSurname?: string | null;
    birthDate?: string | null;
    phone?: string | null;
    email?: string | null;
    gender?: number | null;
    allowSms?: boolean | null;
    allowEmail?: boolean | null;
    address?: Array<CustomerServiceRAddress> | null;
    registered?: boolean;
    lastOrder?: number;
    identificationNumber?: string | null;
    defaultAddress?: number | null;
    invoiceAddress?: number | null;
}

