/**
 * Kiler API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CustomerServiceCustomerAddressRequest { 
    adressId?: number;
    name?: string | null;
    active?: boolean;
    neighborhood?: number;
    building?: string | null;
    floor?: string | null;
    door?: string | null;
    postalCode?: string | null;
    description?: string | null;
    customerName?: string | null;
    customerSurname?: string | null;
    latitude?: number;
    longitude?: number;
    street?: string | null;
    isindividual?: boolean;
    companyName?: string | null;
    taxOffice?: string | null;
    taxNumber?: string | null;
    phoneNumber?: string | null;
}

