/**
 * Kiler API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OrderServiceOrderRequest { 
    deliveryAddressId?: number;
    billingAddressId?: number;
    timeStotId?: number;
    timeSlotId?: number;
    paymentCode?: string | null;
    orderNote?: string | null;
    paymentTypeCode?: string | null;
    deliveryType?: string | null;
    channelId?: number | null;
}

