/**
 * Kiler API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PaymentServicePaymentRequest { 
    cartNumber?: string | null;
    expiryDate?: string | null;
    cartCvv?: string | null;
    posId?: number;
    amount?: number;
    use3dSecure?: boolean;
    transactionUid?: string | null;
    cardType?: number;
}

