/*
 * Kiler API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Kiler.Dotnet.ApiClient.Api;
using Kiler.Dotnet.ApiClient.Model;
using Kiler.Dotnet.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Kiler.Dotnet.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing AccountServiceCheckVersionRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AccountServiceCheckVersionRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AccountServiceCheckVersionRequest
        //private AccountServiceCheckVersionRequest instance;

        public AccountServiceCheckVersionRequestTests()
        {
            // TODO uncomment below to create an instance of AccountServiceCheckVersionRequest
            //instance = new AccountServiceCheckVersionRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AccountServiceCheckVersionRequest
        /// </summary>
        [Fact]
        public void AccountServiceCheckVersionRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" AccountServiceCheckVersionRequest
            //Assert.IsType<AccountServiceCheckVersionRequest>(instance);
        }


        /// <summary>
        /// Test the property 'AppVersion'
        /// </summary>
        [Fact]
        public void AppVersionTest()
        {
            // TODO unit test for the property 'AppVersion'
        }
        /// <summary>
        /// Test the property 'Platform'
        /// </summary>
        [Fact]
        public void PlatformTest()
        {
            // TODO unit test for the property 'Platform'
        }
        /// <summary>
        /// Test the property 'IsWeb'
        /// </summary>
        [Fact]
        public void IsWebTest()
        {
            // TODO unit test for the property 'IsWeb'
        }

    }

}
