/*
 * Kiler API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Kiler.Dotnet.ApiClient.Api;
using Kiler.Dotnet.ApiClient.Model;
using Kiler.Dotnet.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Kiler.Dotnet.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing AdminServiceUpdateRegionNeighborhoodRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AdminServiceUpdateRegionNeighborhoodRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AdminServiceUpdateRegionNeighborhoodRequest
        //private AdminServiceUpdateRegionNeighborhoodRequest instance;

        public AdminServiceUpdateRegionNeighborhoodRequestTests()
        {
            // TODO uncomment below to create an instance of AdminServiceUpdateRegionNeighborhoodRequest
            //instance = new AdminServiceUpdateRegionNeighborhoodRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AdminServiceUpdateRegionNeighborhoodRequest
        /// </summary>
        [Fact]
        public void AdminServiceUpdateRegionNeighborhoodRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" AdminServiceUpdateRegionNeighborhoodRequest
            //Assert.IsType<AdminServiceUpdateRegionNeighborhoodRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Region'
        /// </summary>
        [Fact]
        public void RegionTest()
        {
            // TODO unit test for the property 'Region'
        }
        /// <summary>
        /// Test the property 'Neighborhood'
        /// </summary>
        [Fact]
        public void NeighborhoodTest()
        {
            // TODO unit test for the property 'Neighborhood'
        }

    }

}
