/*
 * Kiler API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Kiler.Dotnet.ApiClient.Api;
using Kiler.Dotnet.ApiClient.Model;
using Kiler.Dotnet.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Kiler.Dotnet.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing AdminServiceBranchResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AdminServiceBranchResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AdminServiceBranchResponse
        //private AdminServiceBranchResponse instance;

        public AdminServiceBranchResponseTests()
        {
            // TODO uncomment below to create an instance of AdminServiceBranchResponse
            //instance = new AdminServiceBranchResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AdminServiceBranchResponse
        /// </summary>
        [Fact]
        public void AdminServiceBranchResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" AdminServiceBranchResponse
            //Assert.IsType<AdminServiceBranchResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Latitude'
        /// </summary>
        [Fact]
        public void LatitudeTest()
        {
            // TODO unit test for the property 'Latitude'
        }
        /// <summary>
        /// Test the property 'Longitude'
        /// </summary>
        [Fact]
        public void LongitudeTest()
        {
            // TODO unit test for the property 'Longitude'
        }

    }

}
