/*
 * Kiler API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Kiler.Dotnet.ApiClient.Api;
using Kiler.Dotnet.ApiClient.Model;
using Kiler.Dotnet.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Kiler.Dotnet.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing AdminServiceAdminNeighborResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AdminServiceAdminNeighborResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AdminServiceAdminNeighborResponse
        //private AdminServiceAdminNeighborResponse instance;

        public AdminServiceAdminNeighborResponseTests()
        {
            // TODO uncomment below to create an instance of AdminServiceAdminNeighborResponse
            //instance = new AdminServiceAdminNeighborResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AdminServiceAdminNeighborResponse
        /// </summary>
        [Fact]
        public void AdminServiceAdminNeighborResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" AdminServiceAdminNeighborResponse
            //Assert.IsType<AdminServiceAdminNeighborResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'CityName'
        /// </summary>
        [Fact]
        public void CityNameTest()
        {
            // TODO unit test for the property 'CityName'
        }
        /// <summary>
        /// Test the property 'CountyName'
        /// </summary>
        [Fact]
        public void CountyNameTest()
        {
            // TODO unit test for the property 'CountyName'
        }
        /// <summary>
        /// Test the property 'Region'
        /// </summary>
        [Fact]
        public void RegionTest()
        {
            // TODO unit test for the property 'Region'
        }
        /// <summary>
        /// Test the property 'RegionName'
        /// </summary>
        [Fact]
        public void RegionNameTest()
        {
            // TODO unit test for the property 'RegionName'
        }
        /// <summary>
        /// Test the property 'GpsId'
        /// </summary>
        [Fact]
        public void GpsIdTest()
        {
            // TODO unit test for the property 'GpsId'
        }
        /// <summary>
        /// Test the property 'Branch'
        /// </summary>
        [Fact]
        public void BranchTest()
        {
            // TODO unit test for the property 'Branch'
        }
        /// <summary>
        /// Test the property 'Population'
        /// </summary>
        [Fact]
        public void PopulationTest()
        {
            // TODO unit test for the property 'Population'
        }

    }

}
