/*
 * Kiler API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Kiler.Dotnet.ApiClient.Api;
using Kiler.Dotnet.ApiClient.Model;
using Kiler.Dotnet.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Kiler.Dotnet.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing CartServiceUpdateCartRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CartServiceUpdateCartRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CartServiceUpdateCartRequest
        //private CartServiceUpdateCartRequest instance;

        public CartServiceUpdateCartRequestTests()
        {
            // TODO uncomment below to create an instance of CartServiceUpdateCartRequest
            //instance = new CartServiceUpdateCartRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CartServiceUpdateCartRequest
        /// </summary>
        [Fact]
        public void CartServiceUpdateCartRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CartServiceUpdateCartRequest
            //Assert.IsType<CartServiceUpdateCartRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Region'
        /// </summary>
        [Fact]
        public void RegionTest()
        {
            // TODO unit test for the property 'Region'
        }
        /// <summary>
        /// Test the property 'ProductId'
        /// </summary>
        [Fact]
        public void ProductIdTest()
        {
            // TODO unit test for the property 'ProductId'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Fact]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
        /// <summary>
        /// Test the property 'CartNote'
        /// </summary>
        [Fact]
        public void CartNoteTest()
        {
            // TODO unit test for the property 'CartNote'
        }
        /// <summary>
        /// Test the property 'ProductNote'
        /// </summary>
        [Fact]
        public void ProductNoteTest()
        {
            // TODO unit test for the property 'ProductNote'
        }

    }

}
