/*
 * Kiler API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Kiler.Dotnet.ApiClient.Api;
using Kiler.Dotnet.ApiClient.Model;
using Kiler.Dotnet.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Kiler.Dotnet.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing CartServiceUpdateTimeslotRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CartServiceUpdateTimeslotRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CartServiceUpdateTimeslotRequest
        //private CartServiceUpdateTimeslotRequest instance;

        public CartServiceUpdateTimeslotRequestTests()
        {
            // TODO uncomment below to create an instance of CartServiceUpdateTimeslotRequest
            //instance = new CartServiceUpdateTimeslotRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CartServiceUpdateTimeslotRequest
        /// </summary>
        [Fact]
        public void CartServiceUpdateTimeslotRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CartServiceUpdateTimeslotRequest
            //Assert.IsType<CartServiceUpdateTimeslotRequest>(instance);
        }


        /// <summary>
        /// Test the property 'TimeStotId'
        /// </summary>
        [Fact]
        public void TimeStotIdTest()
        {
            // TODO unit test for the property 'TimeStotId'
        }

    }

}
