/*
 * Kiler API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Kiler.Dotnet.ApiClient.Api;
using Kiler.Dotnet.ApiClient.Model;
using Kiler.Dotnet.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Kiler.Dotnet.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing CartServiceUpdateCartRegionResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CartServiceUpdateCartRegionResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CartServiceUpdateCartRegionResponse
        //private CartServiceUpdateCartRegionResponse instance;

        public CartServiceUpdateCartRegionResponseTests()
        {
            // TODO uncomment below to create an instance of CartServiceUpdateCartRegionResponse
            //instance = new CartServiceUpdateCartRegionResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CartServiceUpdateCartRegionResponse
        /// </summary>
        [Fact]
        public void CartServiceUpdateCartRegionResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CartServiceUpdateCartRegionResponse
            //Assert.IsType<CartServiceUpdateCartRegionResponse>(instance);
        }


        /// <summary>
        /// Test the property 'CartItemImpacts'
        /// </summary>
        [Fact]
        public void CartItemImpactsTest()
        {
            // TODO unit test for the property 'CartItemImpacts'
        }

    }

}
