/*
 * Kiler API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Kiler.Dotnet.ApiClient.Api;
using Kiler.Dotnet.ApiClient.Model;
using Kiler.Dotnet.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Kiler.Dotnet.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing CartServiceRCartProducts
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CartServiceRCartProductsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CartServiceRCartProducts
        //private CartServiceRCartProducts instance;

        public CartServiceRCartProductsTests()
        {
            // TODO uncomment below to create an instance of CartServiceRCartProducts
            //instance = new CartServiceRCartProducts();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CartServiceRCartProducts
        /// </summary>
        [Fact]
        public void CartServiceRCartProductsInstanceTest()
        {
            // TODO uncomment below to test "IsType" CartServiceRCartProducts
            //Assert.IsType<CartServiceRCartProducts>(instance);
        }


        /// <summary>
        /// Test the property 'RegionProductId'
        /// </summary>
        [Fact]
        public void RegionProductIdTest()
        {
            // TODO unit test for the property 'RegionProductId'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Fact]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
        /// <summary>
        /// Test the property 'ListPrice'
        /// </summary>
        [Fact]
        public void ListPriceTest()
        {
            // TODO unit test for the property 'ListPrice'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Fact]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'DiscountAmount'
        /// </summary>
        [Fact]
        public void DiscountAmountTest()
        {
            // TODO unit test for the property 'DiscountAmount'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'ProductId'
        /// </summary>
        [Fact]
        public void ProductIdTest()
        {
            // TODO unit test for the property 'ProductId'
        }
        /// <summary>
        /// Test the property 'UnitId'
        /// </summary>
        [Fact]
        public void UnitIdTest()
        {
            // TODO unit test for the property 'UnitId'
        }
        /// <summary>
        /// Test the property 'IsActive'
        /// </summary>
        [Fact]
        public void IsActiveTest()
        {
            // TODO unit test for the property 'IsActive'
        }

    }

}
