/*
 * Kiler API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Kiler.Dotnet.ApiClient.Api;
using Kiler.Dotnet.ApiClient.Model;
using Kiler.Dotnet.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Kiler.Dotnet.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerServiceCustomerMessageResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerServiceCustomerMessageResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerServiceCustomerMessageResponse
        //private CustomerServiceCustomerMessageResponse instance;

        public CustomerServiceCustomerMessageResponseTests()
        {
            // TODO uncomment below to create an instance of CustomerServiceCustomerMessageResponse
            //instance = new CustomerServiceCustomerMessageResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerServiceCustomerMessageResponse
        /// </summary>
        [Fact]
        public void CustomerServiceCustomerMessageResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerServiceCustomerMessageResponse
            //Assert.IsType<CustomerServiceCustomerMessageResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Detail'
        /// </summary>
        [Fact]
        public void DetailTest()
        {
            // TODO unit test for the property 'Detail'
        }
        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Fact]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'SendDate'
        /// </summary>
        [Fact]
        public void SendDateTest()
        {
            // TODO unit test for the property 'SendDate'
        }
        /// <summary>
        /// Test the property 'ReadDate'
        /// </summary>
        [Fact]
        public void ReadDateTest()
        {
            // TODO unit test for the property 'ReadDate'
        }

    }

}
