/*
 * Kiler API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Kiler.Dotnet.ApiClient.Api;
using Kiler.Dotnet.ApiClient.Model;
using Kiler.Dotnet.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Kiler.Dotnet.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerServiceDeleteAddressRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerServiceDeleteAddressRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerServiceDeleteAddressRequest
        //private CustomerServiceDeleteAddressRequest instance;

        public CustomerServiceDeleteAddressRequestTests()
        {
            // TODO uncomment below to create an instance of CustomerServiceDeleteAddressRequest
            //instance = new CustomerServiceDeleteAddressRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerServiceDeleteAddressRequest
        /// </summary>
        [Fact]
        public void CustomerServiceDeleteAddressRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerServiceDeleteAddressRequest
            //Assert.IsType<CustomerServiceDeleteAddressRequest>(instance);
        }


        /// <summary>
        /// Test the property 'AddressId'
        /// </summary>
        [Fact]
        public void AddressIdTest()
        {
            // TODO unit test for the property 'AddressId'
        }

    }

}
