/*
 * Kiler API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Kiler.Dotnet.ApiClient.Api;
using Kiler.Dotnet.ApiClient.Model;
using Kiler.Dotnet.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Kiler.Dotnet.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerServiceNewCustomerRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerServiceNewCustomerRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerServiceNewCustomerRequest
        //private CustomerServiceNewCustomerRequest instance;

        public CustomerServiceNewCustomerRequestTests()
        {
            // TODO uncomment below to create an instance of CustomerServiceNewCustomerRequest
            //instance = new CustomerServiceNewCustomerRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerServiceNewCustomerRequest
        /// </summary>
        [Fact]
        public void CustomerServiceNewCustomerRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerServiceNewCustomerRequest
            //Assert.IsType<CustomerServiceNewCustomerRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Surname'
        /// </summary>
        [Fact]
        public void SurnameTest()
        {
            // TODO unit test for the property 'Surname'
        }
        /// <summary>
        /// Test the property 'BirthDate'
        /// </summary>
        [Fact]
        public void BirthDateTest()
        {
            // TODO unit test for the property 'BirthDate'
        }
        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Fact]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'AllowSms'
        /// </summary>
        [Fact]
        public void AllowSmsTest()
        {
            // TODO unit test for the property 'AllowSms'
        }
        /// <summary>
        /// Test the property 'AllowEmail'
        /// </summary>
        [Fact]
        public void AllowEmailTest()
        {
            // TODO unit test for the property 'AllowEmail'
        }
        /// <summary>
        /// Test the property 'Gender'
        /// </summary>
        [Fact]
        public void GenderTest()
        {
            // TODO unit test for the property 'Gender'
        }
        /// <summary>
        /// Test the property 'AllowCampaign'
        /// </summary>
        [Fact]
        public void AllowCampaignTest()
        {
            // TODO unit test for the property 'AllowCampaign'
        }
        /// <summary>
        /// Test the property 'IdentificationNumber'
        /// </summary>
        [Fact]
        public void IdentificationNumberTest()
        {
            // TODO unit test for the property 'IdentificationNumber'
        }

    }

}
