/*
 * Kiler API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Kiler.Dotnet.ApiClient.Api;
using Kiler.Dotnet.ApiClient.Model;
using Kiler.Dotnet.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Kiler.Dotnet.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing CustomerServiceRCustomer
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CustomerServiceRCustomerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CustomerServiceRCustomer
        //private CustomerServiceRCustomer instance;

        public CustomerServiceRCustomerTests()
        {
            // TODO uncomment below to create an instance of CustomerServiceRCustomer
            //instance = new CustomerServiceRCustomer();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CustomerServiceRCustomer
        /// </summary>
        [Fact]
        public void CustomerServiceRCustomerInstanceTest()
        {
            // TODO uncomment below to test "IsType" CustomerServiceRCustomer
            //Assert.IsType<CustomerServiceRCustomer>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'CustomerName'
        /// </summary>
        [Fact]
        public void CustomerNameTest()
        {
            // TODO unit test for the property 'CustomerName'
        }
        /// <summary>
        /// Test the property 'CustomerSurname'
        /// </summary>
        [Fact]
        public void CustomerSurnameTest()
        {
            // TODO unit test for the property 'CustomerSurname'
        }
        /// <summary>
        /// Test the property 'BirthDate'
        /// </summary>
        [Fact]
        public void BirthDateTest()
        {
            // TODO unit test for the property 'BirthDate'
        }
        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Fact]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Gender'
        /// </summary>
        [Fact]
        public void GenderTest()
        {
            // TODO unit test for the property 'Gender'
        }
        /// <summary>
        /// Test the property 'AllowSms'
        /// </summary>
        [Fact]
        public void AllowSmsTest()
        {
            // TODO unit test for the property 'AllowSms'
        }
        /// <summary>
        /// Test the property 'AllowEmail'
        /// </summary>
        [Fact]
        public void AllowEmailTest()
        {
            // TODO unit test for the property 'AllowEmail'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'Registered'
        /// </summary>
        [Fact]
        public void RegisteredTest()
        {
            // TODO unit test for the property 'Registered'
        }
        /// <summary>
        /// Test the property 'LastOrder'
        /// </summary>
        [Fact]
        public void LastOrderTest()
        {
            // TODO unit test for the property 'LastOrder'
        }
        /// <summary>
        /// Test the property 'IdentificationNumber'
        /// </summary>
        [Fact]
        public void IdentificationNumberTest()
        {
            // TODO unit test for the property 'IdentificationNumber'
        }
        /// <summary>
        /// Test the property 'DefaultAddress'
        /// </summary>
        [Fact]
        public void DefaultAddressTest()
        {
            // TODO unit test for the property 'DefaultAddress'
        }
        /// <summary>
        /// Test the property 'InvoiceAddress'
        /// </summary>
        [Fact]
        public void InvoiceAddressTest()
        {
            // TODO unit test for the property 'InvoiceAddress'
        }

    }

}
