/*
 * Kiler API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Kiler.Dotnet.ApiClient.Api;
using Kiler.Dotnet.ApiClient.Model;
using Kiler.Dotnet.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Kiler.Dotnet.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing OrderServiceOrders
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderServiceOrdersTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderServiceOrders
        //private OrderServiceOrders instance;

        public OrderServiceOrdersTests()
        {
            // TODO uncomment below to create an instance of OrderServiceOrders
            //instance = new OrderServiceOrders();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderServiceOrders
        /// </summary>
        [Fact]
        public void OrderServiceOrdersInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderServiceOrders
            //Assert.IsType<OrderServiceOrders>(instance);
        }


        /// <summary>
        /// Test the property 'OrderId'
        /// </summary>
        [Fact]
        public void OrderIdTest()
        {
            // TODO unit test for the property 'OrderId'
        }
        /// <summary>
        /// Test the property 'OrderDate'
        /// </summary>
        [Fact]
        public void OrderDateTest()
        {
            // TODO unit test for the property 'OrderDate'
        }
        /// <summary>
        /// Test the property 'DeliveryAddress'
        /// </summary>
        [Fact]
        public void DeliveryAddressTest()
        {
            // TODO unit test for the property 'DeliveryAddress'
        }
        /// <summary>
        /// Test the property 'DeliveryTypeCode'
        /// </summary>
        [Fact]
        public void DeliveryTypeCodeTest()
        {
            // TODO unit test for the property 'DeliveryTypeCode'
        }
        /// <summary>
        /// Test the property 'BillingAddress'
        /// </summary>
        [Fact]
        public void BillingAddressTest()
        {
            // TODO unit test for the property 'BillingAddress'
        }
        /// <summary>
        /// Test the property 'ProductTotal'
        /// </summary>
        [Fact]
        public void ProductTotalTest()
        {
            // TODO unit test for the property 'ProductTotal'
        }
        /// <summary>
        /// Test the property 'OrderTotal'
        /// </summary>
        [Fact]
        public void OrderTotalTest()
        {
            // TODO unit test for the property 'OrderTotal'
        }
        /// <summary>
        /// Test the property 'ProductDiscountsTotal'
        /// </summary>
        [Fact]
        public void ProductDiscountsTotalTest()
        {
            // TODO unit test for the property 'ProductDiscountsTotal'
        }
        /// <summary>
        /// Test the property 'BagAmount'
        /// </summary>
        [Fact]
        public void BagAmountTest()
        {
            // TODO unit test for the property 'BagAmount'
        }
        /// <summary>
        /// Test the property 'BagTotal'
        /// </summary>
        [Fact]
        public void BagTotalTest()
        {
            // TODO unit test for the property 'BagTotal'
        }
        /// <summary>
        /// Test the property 'OrderNote'
        /// </summary>
        [Fact]
        public void OrderNoteTest()
        {
            // TODO unit test for the property 'OrderNote'
        }
        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Fact]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }
        /// <summary>
        /// Test the property 'CityName'
        /// </summary>
        [Fact]
        public void CityNameTest()
        {
            // TODO unit test for the property 'CityName'
        }
        /// <summary>
        /// Test the property 'CountyName'
        /// </summary>
        [Fact]
        public void CountyNameTest()
        {
            // TODO unit test for the property 'CountyName'
        }
        /// <summary>
        /// Test the property 'PaymentType'
        /// </summary>
        [Fact]
        public void PaymentTypeTest()
        {
            // TODO unit test for the property 'PaymentType'
        }
        /// <summary>
        /// Test the property 'DeliveryTimeStart'
        /// </summary>
        [Fact]
        public void DeliveryTimeStartTest()
        {
            // TODO unit test for the property 'DeliveryTimeStart'
        }
        /// <summary>
        /// Test the property 'DeliveryTimeEnd'
        /// </summary>
        [Fact]
        public void DeliveryTimeEndTest()
        {
            // TODO unit test for the property 'DeliveryTimeEnd'
        }
        /// <summary>
        /// Test the property 'Fee'
        /// </summary>
        [Fact]
        public void FeeTest()
        {
            // TODO unit test for the property 'Fee'
        }
        /// <summary>
        /// Test the property 'Region'
        /// </summary>
        [Fact]
        public void RegionTest()
        {
            // TODO unit test for the property 'Region'
        }
        /// <summary>
        /// Test the property 'EditUntil'
        /// </summary>
        [Fact]
        public void EditUntilTest()
        {
            // TODO unit test for the property 'EditUntil'
        }
        /// <summary>
        /// Test the property 'DeliveryTypeDiscount'
        /// </summary>
        [Fact]
        public void DeliveryTypeDiscountTest()
        {
            // TODO unit test for the property 'DeliveryTypeDiscount'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

    }

}
