/*
 * Kiler API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Kiler.Dotnet.ApiClient.Api;
using Kiler.Dotnet.ApiClient.Model;
using Kiler.Dotnet.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Kiler.Dotnet.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing OrderServiceGetOrderListResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderServiceGetOrderListResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderServiceGetOrderListResponse
        //private OrderServiceGetOrderListResponse instance;

        public OrderServiceGetOrderListResponseTests()
        {
            // TODO uncomment below to create an instance of OrderServiceGetOrderListResponse
            //instance = new OrderServiceGetOrderListResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderServiceGetOrderListResponse
        /// </summary>
        [Fact]
        public void OrderServiceGetOrderListResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderServiceGetOrderListResponse
            //Assert.IsType<OrderServiceGetOrderListResponse>(instance);
        }


        /// <summary>
        /// Test the property 'OrderList'
        /// </summary>
        [Fact]
        public void OrderListTest()
        {
            // TODO unit test for the property 'OrderList'
        }

    }

}
