/*
 * Kiler API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Kiler.Dotnet.ApiClient.Api;
using Kiler.Dotnet.ApiClient.Model;
using Kiler.Dotnet.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Kiler.Dotnet.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing OrderServicePatchOrderRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderServicePatchOrderRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderServicePatchOrderRequest
        //private OrderServicePatchOrderRequest instance;

        public OrderServicePatchOrderRequestTests()
        {
            // TODO uncomment below to create an instance of OrderServicePatchOrderRequest
            //instance = new OrderServicePatchOrderRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderServicePatchOrderRequest
        /// </summary>
        [Fact]
        public void OrderServicePatchOrderRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderServicePatchOrderRequest
            //Assert.IsType<OrderServicePatchOrderRequest>(instance);
        }


        /// <summary>
        /// Test the property 'OrderId'
        /// </summary>
        [Fact]
        public void OrderIdTest()
        {
            // TODO unit test for the property 'OrderId'
        }
        /// <summary>
        /// Test the property 'PaymentCode'
        /// </summary>
        [Fact]
        public void PaymentCodeTest()
        {
            // TODO unit test for the property 'PaymentCode'
        }

    }

}
