/*
 * Kiler API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Kiler.Dotnet.ApiClient.Api;
using Kiler.Dotnet.ApiClient.Model;
using Kiler.Dotnet.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Kiler.Dotnet.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentServicePaymentTransactionRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentServicePaymentTransactionRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentServicePaymentTransactionRequest
        //private PaymentServicePaymentTransactionRequest instance;

        public PaymentServicePaymentTransactionRequestTests()
        {
            // TODO uncomment below to create an instance of PaymentServicePaymentTransactionRequest
            //instance = new PaymentServicePaymentTransactionRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentServicePaymentTransactionRequest
        /// </summary>
        [Fact]
        public void PaymentServicePaymentTransactionRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentServicePaymentTransactionRequest
            //Assert.IsType<PaymentServicePaymentTransactionRequest>(instance);
        }


        /// <summary>
        /// Test the property 'TransactionUid'
        /// </summary>
        [Fact]
        public void TransactionUidTest()
        {
            // TODO unit test for the property 'TransactionUid'
        }

    }

}
