/*
 * Kiler API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Kiler.Dotnet.ApiClient.Api;
using Kiler.Dotnet.ApiClient.Model;
using Kiler.Dotnet.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Kiler.Dotnet.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentServicePaymentRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentServicePaymentRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentServicePaymentRequest
        //private PaymentServicePaymentRequest instance;

        public PaymentServicePaymentRequestTests()
        {
            // TODO uncomment below to create an instance of PaymentServicePaymentRequest
            //instance = new PaymentServicePaymentRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentServicePaymentRequest
        /// </summary>
        [Fact]
        public void PaymentServicePaymentRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaymentServicePaymentRequest
            //Assert.IsType<PaymentServicePaymentRequest>(instance);
        }


        /// <summary>
        /// Test the property 'CartNumber'
        /// </summary>
        [Fact]
        public void CartNumberTest()
        {
            // TODO unit test for the property 'CartNumber'
        }
        /// <summary>
        /// Test the property 'ExpiryDate'
        /// </summary>
        [Fact]
        public void ExpiryDateTest()
        {
            // TODO unit test for the property 'ExpiryDate'
        }
        /// <summary>
        /// Test the property 'CartCvv'
        /// </summary>
        [Fact]
        public void CartCvvTest()
        {
            // TODO unit test for the property 'CartCvv'
        }
        /// <summary>
        /// Test the property 'PosId'
        /// </summary>
        [Fact]
        public void PosIdTest()
        {
            // TODO unit test for the property 'PosId'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'Use3dSecure'
        /// </summary>
        [Fact]
        public void Use3dSecureTest()
        {
            // TODO unit test for the property 'Use3dSecure'
        }
        /// <summary>
        /// Test the property 'TransactionUid'
        /// </summary>
        [Fact]
        public void TransactionUidTest()
        {
            // TODO unit test for the property 'TransactionUid'
        }
        /// <summary>
        /// Test the property 'CardType'
        /// </summary>
        [Fact]
        public void CardTypeTest()
        {
            // TODO unit test for the property 'CardType'
        }

    }

}
