/*
 * Kiler API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Kiler.Dotnet.ApiClient.Api;
using Kiler.Dotnet.ApiClient.Model;
using Kiler.Dotnet.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Kiler.Dotnet.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing ProductServiceProductAlternativesRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ProductServiceProductAlternativesRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ProductServiceProductAlternativesRequest
        //private ProductServiceProductAlternativesRequest instance;

        public ProductServiceProductAlternativesRequestTests()
        {
            // TODO uncomment below to create an instance of ProductServiceProductAlternativesRequest
            //instance = new ProductServiceProductAlternativesRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ProductServiceProductAlternativesRequest
        /// </summary>
        [Fact]
        public void ProductServiceProductAlternativesRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ProductServiceProductAlternativesRequest
            //Assert.IsType<ProductServiceProductAlternativesRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Product'
        /// </summary>
        [Fact]
        public void ProductTest()
        {
            // TODO unit test for the property 'Product'
        }

    }

}
