/*
 * Kiler API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Kiler.Dotnet.ApiClient.Api;
using Kiler.Dotnet.ApiClient.Model;
using Kiler.Dotnet.ApiClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Kiler.Dotnet.ApiClient.Test.Model
{
    /// <summary>
    ///  Class for testing RestResultOfPaymentServiceSodexoPaymentResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RestResultOfPaymentServiceSodexoPaymentResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RestResultOfPaymentServiceSodexoPaymentResponse
        //private RestResultOfPaymentServiceSodexoPaymentResponse instance;

        public RestResultOfPaymentServiceSodexoPaymentResponseTests()
        {
            // TODO uncomment below to create an instance of RestResultOfPaymentServiceSodexoPaymentResponse
            //instance = new RestResultOfPaymentServiceSodexoPaymentResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RestResultOfPaymentServiceSodexoPaymentResponse
        /// </summary>
        [Fact]
        public void RestResultOfPaymentServiceSodexoPaymentResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" RestResultOfPaymentServiceSodexoPaymentResponse
            //Assert.IsType<RestResultOfPaymentServiceSodexoPaymentResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

    }

}
