/*
 * Kiler API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Kiler.Dotnet.ApiClient.Client.OpenAPIDateConverter;

namespace Kiler.Dotnet.ApiClient.Model
{
    /// <summary>
    /// CartServiceUpdateCartRegionRequest
    /// </summary>
    [DataContract(Name = "CartServiceUpdateCartRegionRequest")]
    public partial class CartServiceUpdateCartRegionRequest : IEquatable<CartServiceUpdateCartRegionRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CartServiceUpdateCartRegionRequest" /> class.
        /// </summary>
        /// <param name="neighborhoodId">neighborhoodId.</param>
        /// <param name="regionId">regionId.</param>
        /// <param name="isForce">isForce.</param>
        public CartServiceUpdateCartRegionRequest(int? neighborhoodId = default(int?), int? regionId = default(int?), bool isForce = default(bool))
        {
            this.NeighborhoodId = neighborhoodId;
            this.RegionId = regionId;
            this.IsForce = isForce;
        }

        /// <summary>
        /// Gets or Sets NeighborhoodId
        /// </summary>
        [DataMember(Name = "neighborhoodId", EmitDefaultValue = true)]
        public int? NeighborhoodId { get; set; }

        /// <summary>
        /// Gets or Sets RegionId
        /// </summary>
        [DataMember(Name = "regionId", EmitDefaultValue = true)]
        public int? RegionId { get; set; }

        /// <summary>
        /// Gets or Sets IsForce
        /// </summary>
        [DataMember(Name = "isForce", EmitDefaultValue = true)]
        public bool IsForce { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CartServiceUpdateCartRegionRequest {\n");
            sb.Append("  NeighborhoodId: ").Append(NeighborhoodId).Append("\n");
            sb.Append("  RegionId: ").Append(RegionId).Append("\n");
            sb.Append("  IsForce: ").Append(IsForce).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CartServiceUpdateCartRegionRequest);
        }

        /// <summary>
        /// Returns true if CartServiceUpdateCartRegionRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of CartServiceUpdateCartRegionRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CartServiceUpdateCartRegionRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.NeighborhoodId == input.NeighborhoodId ||
                    (this.NeighborhoodId != null &&
                    this.NeighborhoodId.Equals(input.NeighborhoodId))
                ) && 
                (
                    this.RegionId == input.RegionId ||
                    (this.RegionId != null &&
                    this.RegionId.Equals(input.RegionId))
                ) && 
                (
                    this.IsForce == input.IsForce ||
                    this.IsForce.Equals(input.IsForce)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.NeighborhoodId != null)
                {
                    hashCode = (hashCode * 59) + this.NeighborhoodId.GetHashCode();
                }
                if (this.RegionId != null)
                {
                    hashCode = (hashCode * 59) + this.RegionId.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.IsForce.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
