/*
 * Kiler API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Kiler.Dotnet.ApiClient.Client;
using Kiler.Dotnet.ApiClient.Api;
// uncomment below to import models
//using Kiler.Dotnet.ApiClient.Model;

namespace Kiler.Dotnet.ApiClient.Test.Api
{
    /// <summary>
    ///  Class for testing AffiliateApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class AffiliateApiTests : IDisposable
    {
        private AffiliateApi instance;

        public AffiliateApiTests()
        {
            instance = new AffiliateApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AffiliateApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' AffiliateApi
            //Assert.IsType<AffiliateApi>(instance);
        }

        /// <summary>
        /// Test ApiAffiliateDetailUrllinkGet
        /// </summary>
        [Fact]
        public void ApiAffiliateDetailUrllinkGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string urlLink = null;
            //instance.ApiAffiliateDetailUrllinkGet(urlLink);
        }

        /// <summary>
        /// Test ApiAffiliateGetShareLinkPost
        /// </summary>
        [Fact]
        public void ApiAffiliateGetShareLinkPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AffiliateServiceLinkRequest body = null;
            //var response = instance.ApiAffiliateGetShareLinkPost(body);
            //Assert.IsType<string>(response);
        }

        /// <summary>
        /// Test ApiAffiliateShareLinkClickedPost
        /// </summary>
        [Fact]
        public void ApiAffiliateShareLinkClickedPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string key = null;
            //var response = instance.ApiAffiliateShareLinkClickedPost(key);
            //Assert.IsType<bool>(response);
        }
    }
}
