/*
 * Kiler API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Kiler.Dotnet.ApiClient.Client;
using Kiler.Dotnet.ApiClient.Api;
// uncomment below to import models
//using Kiler.Dotnet.ApiClient.Model;

namespace Kiler.Dotnet.ApiClient.Test.Api
{
    /// <summary>
    ///  Class for testing BannerApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class BannerApiTests : IDisposable
    {
        private BannerApi instance;

        public BannerApiTests()
        {
            instance = new BannerApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BannerApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' BannerApi
            //Assert.IsType<BannerApi>(instance);
        }

        /// <summary>
        /// Test ApiBannerGetBannersPost
        /// </summary>
        [Fact]
        public void ApiBannerGetBannersPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiBannerGetBannersPost();
            //Assert.IsType<RestResultOfBannerServiceBannerResponse>(response);
        }

        /// <summary>
        /// Test ApiBannerUpdateBannerPost
        /// </summary>
        [Fact]
        public void ApiBannerUpdateBannerPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //BannerServiceBannerRequest body = null;
            //var response = instance.ApiBannerUpdateBannerPost(body);
            //Assert.IsType<RestResultOfBannerServiceBannerResponse>(response);
        }
    }
}
