/*
 * Kiler API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Kiler.Dotnet.ApiClient.Client;
using Kiler.Dotnet.ApiClient.Api;

namespace Kiler.Dotnet.ApiClient.Test.Api
{
    /// <summary>
    ///  Class for testing MigrationApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class MigrationApiTests : IDisposable
    {
        private MigrationApi instance;

        public MigrationApiTests()
        {
            instance = new MigrationApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MigrationApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' MigrationApi
            //Assert.IsType<MigrationApi>(instance);
        }

        /// <summary>
        /// Test ApiMigrationCreateregionpriceGet
        /// </summary>
        [Fact]
        public void ApiMigrationCreateregionpriceGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ApiMigrationCreateregionpriceGet();
            //Assert.IsType<bool>(response);
        }

        /// <summary>
        /// Test ApiMigrationUpdateCitiesFromRestGet
        /// </summary>
        [Fact]
        public void ApiMigrationUpdateCitiesFromRestGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.ApiMigrationUpdateCitiesFromRestGet();
        }
    }
}
