/**
 * Kiler API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AccountServiceCheckVersionRequest } from '../model/models';
import { AccountServiceLoginRequest } from '../model/models';
import { RestResultOfAccountServiceCheckVersionResponse } from '../model/models';
import { RestResultOfAccountServiceLoginResponse } from '../model/models';
import { RestResultOfSystemBoolean } from '../model/models';
import { RestResultOfSystemObject } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AccountServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param accountServiceCheckVersionRequest 
     */
    apiAccountCheckversionPost(accountServiceCheckVersionRequest?: AccountServiceCheckVersionRequest, extraHttpRequestParams?: any): Observable<RestResultOfAccountServiceCheckVersionResponse>;

    /**
     * 
     * 
     */
    apiAccountDeleteAccountDelete(extraHttpRequestParams?: any): Observable<RestResultOfSystemBoolean>;

    /**
     * 
     * 
     */
    apiAccountFirebaseTokenGet(extraHttpRequestParams?: any): Observable<string>;

    /**
     * 
     * 
     * @param accountServiceLoginRequest 
     */
    apiAccountLoginPost(accountServiceLoginRequest?: AccountServiceLoginRequest, extraHttpRequestParams?: any): Observable<RestResultOfAccountServiceLoginResponse>;

    /**
     * 
     * 
     */
    apiAccountLogoutGet(extraHttpRequestParams?: any): Observable<boolean>;

    /**
     * 
     * 
     */
    apiAccountWhoAmIGet(extraHttpRequestParams?: any): Observable<RestResultOfSystemObject>;

}
