export * from './account.service';
import { AccountService } from './account.service';
export * from './admin.service';
import { AdminService } from './admin.service';
export * from './affiliate.service';
import { AffiliateService } from './affiliate.service';
export * from './banner.service';
import { BannerService } from './banner.service';
export * from './cart.service';
import { CartService } from './cart.service';
export * from './catalog.service';
import { CatalogService } from './catalog.service';
export * from './crm.service';
import { CrmService } from './crm.service';
export * from './customer.service';
import { CustomerService } from './customer.service';
export * from './definition.service';
import { DefinitionService } from './definition.service';
export * from './integration.service';
import { IntegrationService } from './integration.service';
export * from './migration.service';
import { MigrationService } from './migration.service';
export * from './order.service';
import { OrderService } from './order.service';
export * from './payment.service';
import { PaymentService } from './payment.service';
export * from './product.service';
import { ProductService } from './product.service';
export * from './register.service';
import { RegisterService } from './register.service';
export const APIS = [AccountService, AdminService, AffiliateService, BannerService, CartService, CatalogService, CrmService, CustomerService, DefinitionService, IntegrationService, MigrationService, OrderService, PaymentService, ProductService, RegisterService];
