/**
 * Kiler API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { DefinitionServiceCountiesRequest } from '../model/models';
import { DefinitionServiceNeighborRequest } from '../model/models';
import { DefinitionServiceUpdateAgreementRequest } from '../model/models';
import { RestResultOfDefinitionServiceUpdateAgreementLogResponse } from '../model/models';
import { RestResultOfDefinitionServiceUploadCountriesResponse } from '../model/models';
import { RestResultOfListOfDefinitionServiceAgreementResponse } from '../model/models';
import { RestResultOfListOfDefinitionServiceCitiesResponse } from '../model/models';
import { RestResultOfListOfDefinitionServiceCountiesResponse } from '../model/models';
import { RestResultOfListOfDefinitionServiceDeliveryType } from '../model/models';
import { RestResultOfListOfDefinitionServiceFaqResponse } from '../model/models';
import { RestResultOfListOfDefinitionServiceNeighborResponse } from '../model/models';
import { RestResultOfListOfDefinitionServiceSelfPickupPoint } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface DefinitionServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param getAcceptedAgreement 
     */
    apiDefinitionAgreementGet(getAcceptedAgreement?: boolean, extraHttpRequestParams?: any): Observable<RestResultOfListOfDefinitionServiceAgreementResponse>;

    /**
     * 
     * 
     */
    apiDefinitionCitiesPost(extraHttpRequestParams?: any): Observable<RestResultOfListOfDefinitionServiceCitiesResponse>;

    /**
     * 
     * 
     * @param definitionServiceCountiesRequest 
     */
    apiDefinitionCountiesPost(definitionServiceCountiesRequest?: DefinitionServiceCountiesRequest, extraHttpRequestParams?: any): Observable<RestResultOfListOfDefinitionServiceCountiesResponse>;

    /**
     * 
     * 
     */
    apiDefinitionDeliveryTypesGet(extraHttpRequestParams?: any): Observable<RestResultOfListOfDefinitionServiceDeliveryType>;

    /**
     * 
     * 
     */
    apiDefinitionFaqGet(extraHttpRequestParams?: any): Observable<RestResultOfListOfDefinitionServiceFaqResponse>;

    /**
     * 
     * 
     */
    apiDefinitionGetAllSelfPickupPointsGet(extraHttpRequestParams?: any): Observable<RestResultOfListOfDefinitionServiceSelfPickupPoint>;

    /**
     * 
     * 
     * @param countyId 
     */
    apiDefinitionGetSelfPickupPointInCountyGet(countyId?: number, extraHttpRequestParams?: any): Observable<RestResultOfListOfDefinitionServiceSelfPickupPoint>;

    /**
     * 
     * 
     * @param cityId 
     */
    apiDefinitionGetSelfPickupPointsInCityGet(cityId?: number, extraHttpRequestParams?: any): Observable<RestResultOfListOfDefinitionServiceSelfPickupPoint>;

    /**
     * 
     * 
     * @param neighborhood 
     */
    apiDefinitionGetSelfPickupPointsInNeighborhoodGet(neighborhood?: number, extraHttpRequestParams?: any): Observable<RestResultOfListOfDefinitionServiceSelfPickupPoint>;

    /**
     * 
     * 
     */
    apiDefinitionHelloGet(extraHttpRequestParams?: any): Observable<string>;

    /**
     * 
     * 
     * @param definitionServiceNeighborRequest 
     */
    apiDefinitionNeighborhoodPost(definitionServiceNeighborRequest?: DefinitionServiceNeighborRequest, extraHttpRequestParams?: any): Observable<RestResultOfListOfDefinitionServiceNeighborResponse>;

    /**
     * 
     * 
     * @param definitionServiceUpdateAgreementRequest 
     */
    apiDefinitionUpdateAgreementLogPost(definitionServiceUpdateAgreementRequest?: DefinitionServiceUpdateAgreementRequest, extraHttpRequestParams?: any): Observable<RestResultOfDefinitionServiceUpdateAgreementLogResponse>;

    /**
     * 
     * 
     */
    apiDefinitionUploadCountriesToFirebasePost(extraHttpRequestParams?: any): Observable<RestResultOfDefinitionServiceUploadCountriesResponse>;

}
