/**
 * Kiler API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AdminServiceTimeSlotResponse {
    'start'?: Date;
    'end'?: Date;
    'quota'?: number;
    'region'?: number;
    'fee'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "start",
            "baseName": "start",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "end",
            "baseName": "end",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "quota",
            "baseName": "quota",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "region",
            "baseName": "region",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "fee",
            "baseName": "fee",
            "type": "number",
            "format": "double"
        }    ];

    static getAttributeTypeMap() {
        return AdminServiceTimeSlotResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

