/**
 * Kiler API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class BannerServiceRBanner {
    'name'?: string | null;
    'active'?: boolean;
    'image'?: string | null;
    'webImage'?: string | null;
    'index'?: number;
    'id'?: number;
    'navigationTypeCode'?: string | null;
    'navigationId'?: number | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "image",
            "baseName": "image",
            "type": "string",
            "format": ""
        },
        {
            "name": "webImage",
            "baseName": "webImage",
            "type": "string",
            "format": ""
        },
        {
            "name": "index",
            "baseName": "index",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "navigationTypeCode",
            "baseName": "navigationTypeCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "navigationId",
            "baseName": "navigationId",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return BannerServiceRBanner.attributeTypeMap;
    }

    public constructor() {
    }
}

