/**
 * Kiler API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CartServiceCampaignResponse {
    'id'?: number;
    'name'?: string | null;
    'description'?: string | null;
    'image'?: string | null;
    'smallImage'?: string | null;
    'conditions'?: string | null;
    'displayPriority'?: number | null;
    'productIds'?: Array<number> | null;
    'discount'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "image",
            "baseName": "image",
            "type": "string",
            "format": ""
        },
        {
            "name": "smallImage",
            "baseName": "smallImage",
            "type": "string",
            "format": ""
        },
        {
            "name": "conditions",
            "baseName": "conditions",
            "type": "string",
            "format": ""
        },
        {
            "name": "displayPriority",
            "baseName": "displayPriority",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "productIds",
            "baseName": "productIds",
            "type": "Array<number>",
            "format": "int32"
        },
        {
            "name": "discount",
            "baseName": "discount",
            "type": "number",
            "format": "double"
        }    ];

    static getAttributeTypeMap() {
        return CartServiceCampaignResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

