/**
 * Kiler API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CartServiceCampaignResponse } from '../models/CartServiceCampaignResponse';
import { CartServiceRCartProducts } from '../models/CartServiceRCartProducts';
import { HttpFile } from '../http/http';

export class CartServiceCartResponse {
    'cartId'?: number;
    'customer'?: number | null;
    'cartTotal'?: number | null;
    'regionId'?: number | null;
    'deviceToken'?: string | null;
    'bagTotal'?: number | null;
    'bagAmount'?: number | null;
    'estimatedFee'?: number | null;
    'appliedCampaigns'?: Array<CartServiceCampaignResponse> | null;
    'campaignTotalDiscount'?: number | null;
    'cartProducts'?: Array<CartServiceRCartProducts> | null;
    'cardProducts'?: Array<CartServiceRCartProducts> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "cartId",
            "baseName": "cartId",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "customer",
            "baseName": "customer",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "cartTotal",
            "baseName": "cartTotal",
            "type": "number",
            "format": "double"
        },
        {
            "name": "regionId",
            "baseName": "regionId",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "deviceToken",
            "baseName": "deviceToken",
            "type": "string",
            "format": ""
        },
        {
            "name": "bagTotal",
            "baseName": "bagTotal",
            "type": "number",
            "format": "double"
        },
        {
            "name": "bagAmount",
            "baseName": "bagAmount",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "estimatedFee",
            "baseName": "estimatedFee",
            "type": "number",
            "format": "double"
        },
        {
            "name": "appliedCampaigns",
            "baseName": "appliedCampaigns",
            "type": "Array<CartServiceCampaignResponse>",
            "format": ""
        },
        {
            "name": "campaignTotalDiscount",
            "baseName": "campaignTotalDiscount",
            "type": "number",
            "format": "double"
        },
        {
            "name": "cartProducts",
            "baseName": "cartProducts",
            "type": "Array<CartServiceRCartProducts>",
            "format": ""
        },
        {
            "name": "cardProducts",
            "baseName": "cardProducts",
            "type": "Array<CartServiceRCartProducts>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CartServiceCartResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

