/**
 * Kiler API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CatalogServiceRProduct } from '../models/CatalogServiceRProduct';
import { HttpFile } from '../http/http';

export class CatalogServiceRCategory {
    'id'?: number;
    'parentId'?: number;
    'name'?: string | null;
    'products'?: Array<CatalogServiceRProduct> | null;
    'subCategories'?: Array<CatalogServiceRCategory> | null;
    'order'?: number;
    'menuName'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "parentId",
            "baseName": "parentId",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "products",
            "baseName": "products",
            "type": "Array<CatalogServiceRProduct>",
            "format": ""
        },
        {
            "name": "subCategories",
            "baseName": "subCategories",
            "type": "Array<CatalogServiceRCategory>",
            "format": ""
        },
        {
            "name": "order",
            "baseName": "order",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "menuName",
            "baseName": "menuName",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CatalogServiceRCategory.attributeTypeMap;
    }

    public constructor() {
    }
}

