/**
 * Kiler API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CustomerServiceRAddress } from '../models/CustomerServiceRAddress';
import { HttpFile } from '../http/http';

export class CustomerServiceRCustomer {
    'id'?: number;
    'customerName'?: string | null;
    'customerSurname'?: string | null;
    'birthDate'?: Date | null;
    'phone'?: string | null;
    'email'?: string | null;
    'gender'?: number | null;
    'allowSms'?: boolean | null;
    'allowEmail'?: boolean | null;
    'address'?: Array<CustomerServiceRAddress> | null;
    'registered'?: boolean;
    'lastOrder'?: number;
    'identificationNumber'?: string | null;
    'defaultAddress'?: number | null;
    'invoiceAddress'?: number | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "customerName",
            "baseName": "customerName",
            "type": "string",
            "format": ""
        },
        {
            "name": "customerSurname",
            "baseName": "customerSurname",
            "type": "string",
            "format": ""
        },
        {
            "name": "birthDate",
            "baseName": "birthDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string",
            "format": ""
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "gender",
            "baseName": "gender",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "allowSms",
            "baseName": "allowSms",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "allowEmail",
            "baseName": "allowEmail",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "Array<CustomerServiceRAddress>",
            "format": ""
        },
        {
            "name": "registered",
            "baseName": "registered",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "lastOrder",
            "baseName": "lastOrder",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "identificationNumber",
            "baseName": "identificationNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "defaultAddress",
            "baseName": "defaultAddress",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "invoiceAddress",
            "baseName": "invoiceAddress",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return CustomerServiceRCustomer.attributeTypeMap;
    }

    public constructor() {
    }
}

