/**
 * Kiler API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class OrderServiceUpdateOrderRequest {
    'orderId'?: number;
    'orderStatusId'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "orderId",
            "baseName": "orderId",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "orderStatusId",
            "baseName": "orderStatusId",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return OrderServiceUpdateOrderRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

