/**
 * Kiler API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RegisterServiceVersionResponse } from '../models/RegisterServiceVersionResponse';
import { HttpFile } from '../http/http';

export class RegisterServiceLoginResponse {
    'token'?: string | null;
    'customerId'?: number | null;
    'registered'?: boolean;
    'firebaseToken'?: string | null;
    'versionResponse'?: RegisterServiceVersionResponse;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "token",
            "baseName": "token",
            "type": "string",
            "format": ""
        },
        {
            "name": "customerId",
            "baseName": "customerId",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "registered",
            "baseName": "registered",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "firebaseToken",
            "baseName": "firebaseToken",
            "type": "string",
            "format": ""
        },
        {
            "name": "versionResponse",
            "baseName": "versionResponse",
            "type": "RegisterServiceVersionResponse",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RegisterServiceLoginResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

