/**
 * Kiler API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class RegisterServiceVerifyRequest {
    'phone'?: string | null;
    'smsCode'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "phone",
            "baseName": "phone",
            "type": "string",
            "format": ""
        },
        {
            "name": "smsCode",
            "baseName": "smsCode",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RegisterServiceVerifyRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

