/**
 * Kiler API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DefinitionServiceCountiesResponse } from '../models/DefinitionServiceCountiesResponse';
import { HttpFile } from '../http/http';

export class RestResultOfListOfDefinitionServiceCountiesResponse {
    'success'?: boolean;
    'message'?: string | null;
    'data'?: Array<DefinitionServiceCountiesResponse> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "success",
            "baseName": "success",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<DefinitionServiceCountiesResponse>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RestResultOfListOfDefinitionServiceCountiesResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

